name: "Linux build"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-22.04]
        cc: [gcc-11]
        cxx: [g++-11]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Install compilers
      run: sudo apt install ${{matrix.cc}} ${{matrix.cxx}}

    - name: Install dependencies
      run: sudo apt install libxrandr-dev libxinerama-dev libxi-dev libxcursor-dev libglu1-mesa-dev

    - name: Configure CMake
      env:
        CC: ${{matrix.cc}}
        CXX: ${{matrix.cxx}}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Install
      run: sudo cmake --install ${{github.workspace}}/build
