name: "Windows build"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [windows-2019]
        platform: [Win32, x64]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Prepare submodules
      run: |
        git submodule init
        git submodule update

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -A ${{matrix.platform}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}
